sudo: false

language: node_js

node_js:
  - 9

install:
  - npm install

script:
  - npm run clean
  - npm run make
  - npm run build:webpack
  - npm run clean
  - npm run build:parcel  
